[package]
name = "tflgtfs"
version = "0.1.0"
authors = ["Tom Burdick <thomas.burdick@gmail.com>"]

[dependencies]
ansi_term = "0.7"
clap = "2.1"
csv = "0.14"
env_logger = "0.3"
hyper = "0.8"
log = "0.3"
rustc-serialize = "0.3"
scoped_threadpool = "0.1"
